num1 = input("Hello! Please input your first number: ")
num2 = input("Thank you, please enter your second number: ")
add = float(num1) + float(num2)
subtract = float(num1) - float(num2)
print("Your addition output is " + str(add))
print("Your subtraction output is: " + str(subtract))
